// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLwpoA2JfuSQT1WZTSQcS0fo3vPLLGhSs',
    appId: '1:198544335231:web:5d036f413f35193f92ba4a',
    messagingSenderId: '198544335231',
    projectId: 'flutter-rpg-f22e4',
    authDomain: 'flutter-rpg-f22e4.firebaseapp.com',
    storageBucket: 'flutter-rpg-f22e4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNtQ2hInqasKrb5KotM1bP6ncr-8jcVxo',
    appId: '1:198544335231:android:e2268cf9430240a492ba4a',
    messagingSenderId: '198544335231',
    projectId: 'flutter-rpg-f22e4',
    storageBucket: 'flutter-rpg-f22e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFXEfZqkajRD6ZUdNzC4v6lcI5UfZU-uc',
    appId: '1:198544335231:ios:546e2c05af82b13392ba4a',
    messagingSenderId: '198544335231',
    projectId: 'flutter-rpg-f22e4',
    storageBucket: 'flutter-rpg-f22e4.firebasestorage.app',
    iosBundleId: 'com.example.flutterRpg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFXEfZqkajRD6ZUdNzC4v6lcI5UfZU-uc',
    appId: '1:198544335231:ios:546e2c05af82b13392ba4a',
    messagingSenderId: '198544335231',
    projectId: 'flutter-rpg-f22e4',
    storageBucket: 'flutter-rpg-f22e4.firebasestorage.app',
    iosBundleId: 'com.example.flutterRpg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLwpoA2JfuSQT1WZTSQcS0fo3vPLLGhSs',
    appId: '1:198544335231:web:038e5b72e99923f592ba4a',
    messagingSenderId: '198544335231',
    projectId: 'flutter-rpg-f22e4',
    authDomain: 'flutter-rpg-f22e4.firebaseapp.com',
    storageBucket: 'flutter-rpg-f22e4.firebasestorage.app',
  );
}
